# TCA-InfraForge Kind Cluster Configuration
# Optimized for GitOps demonstration

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tca-infraforge-demo

nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "tca.infraforge/node-role=control-plane,tca.infraforge/demo=true"
  
  # Port mappings using uncommon ports to avoid conflicts
  extraPortMappings:
  - containerPort: 80
    hostPort: 8070      # ArgoCD HTTP (was 8080)
    protocol: TCP
  - containerPort: 443  
    hostPort: 8470      # ArgoCD HTTPS (was 8443)
    protocol: TCP
  - containerPort: 9000
    hostPort: 9070      # Traefik Dashboard (was 9080)
    protocol: TCP
  - containerPort: 3000
    hostPort: 3070      # Grafana (was 3000)
    protocol: TCP
  - containerPort: 16686
    hostPort: 16670     # Jaeger UI (uncommon port)
    protocol: TCP

# Networking configuration for TCA demo
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6470     # API Server (was 6443)
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  
# Feature gates for advanced Kubernetes features
featureGates:
  "EphemeralContainers": true
  "GracefulNodeShutdown": true